### ISSUE TITLE
Folder Name "Providers"

### ISSUE THREAD

**Issue by samueldotfr** [Itsdenty/adonis-swagger-jsdoc#1]
Hello,

The first letter of your folder "Providers" is uppercase, it is a bit confusing because all common providers folders are lowercase,

Thanks for your job,

Sam

**Comment by Itsdenty** [comment]
Thank you, Sam, for the feedback. It must have been an oversight from my end, I will push a fix for it.

**Comment by Itsdenty** [comment]
I have fixed the issue.
